version: '3.5'
services:
    statsd:
        image: hopsoft/graphite-statsd
        networks:
            - skynet
        environment:
            - GRAPHITE_TIME_ZONE=America/Los_Angeles
            - GF_AUTH_LDAP_ENABLED=true
            - GF_AUTH_LDAP_CONFIG_FILE=/run/secrets/ldap.toml
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_USERS_LOGIN_HINT=username
        volumes:
            -   type: bind
                source: /var/nfsshare/logs/graphite
                target: /opt/graphite/storage
        secrets:
            - ldap.toml
        ports:
            - "81:81"
            - "8126:8126"

    grafana:
        image: grafana/grafana
        networks:
            - skynet
        environment:
            # check recent grafana version to make sure these vars still work
            - GF_AUTH_LDAP_ENABLED=true
            - GF_AUTH_LDAP_CONFIG_FILE=/run/secrets/ldap.toml
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_USERS_LOGIN_HINT=username
        volumes:
            -   type: bind
                source: /var/nfsshare/logs/grafana
                target: /var/lib/grafana
        secrets:
            - ldap.toml
        ports:
            - "3000:3000"

secrets:
    ldap.toml:
        file: ./secrets/ldap.toml
